# Model
device: 6

name: hugging_cache/llava-v1.5-7b
model_name: llava
model_class: LLaVA
small_name: hugging_cache/vicuna-7b-v1.5
tokenizer_class: LlamaTokenizer
tokenizer_name: hugging_cache/llava-v1.5-7b
cls_name: hugging_cache/distilbert-base-cased
cls_class: AutoModel 
inner_params: []
# - model.layers.29.mlp.down_proj.weight
# - model.layers.29.mlp.up_proj.weight
# - model.layers.30.mlp.down_proj.weight
# - model.layers.30.mlp.up_proj.weight
# - model.layers.31.mlp.down_proj.weight
# - model.layers.31.mlp.up_proj.weight

# For OURS
query_generate: False
query_prompt_dir: datasets/prompt
train_port: True
train_adapter: False
only_text: False # 이미지는 활용안하고 텍스트만 사용했을때의 결과 

# For LORA
use_lora: False
lora_edit_lr: 1e-5
lora_r: 8
lora_alpha: 32
lora_dropout: 0.1
lora_target_modules:
  - down_proj
  - up_proj


# Method
alg: OURS
alg_name: OURS
num_steps: 10
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null
archive: null

batch_size: 1
model_save_pt: 5000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 50000
log_interval: 100
val_interval: 5000
early_stop_patience: 10000
early_stop_key: "loss/total_edit_val"
eval_only: False
half: False
save: False
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 1
val_steps: 500
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results

# Multimodal
qformer_checkpoint: null
qformer_name_or_path: null
state_dict_file: null
pretrained_ckpt: null

# image
coco_image: datasets/VLKEB_images/mmkb_images
rephrase_image: datasets/VLKEB_images/mmkb_images