# Model
device: 4

name: liuhaotian/llava-v1.5-7b
model_name: llava
model_class: LLaVA
small_name: lmsys/vicuna-7b-v1.5
tokenizer_class: LlamaTokenizer
tokenizer_name: liuhaotian/llava-v1.5-7b
cls_name: distilbert/distilbert-base-cased
cls_class: AutoModel 
inner_params:
- model.layers.29.mlp.down_proj.weight
- model.layers.29.mlp.up_proj.weight
- model.layers.30.mlp.down_proj.weight
- model.layers.30.mlp.up_proj.weight
- model.layers.31.mlp.down_proj.weight
- model.layers.31.mlp.up_proj.weight


# Method
alg: SERAC_MULTI
lr: 1e-5
edit_lr: 1e-2
seed: 0
lr_lr: 0.0
cedit: 0.1
iedit: 0.1
cloc: 1.0
cbase: 1.0
dropout: 0.0
final_eval: True
supervised: False
train_base: False
no_grad_layers: null
soft_weighting: False
checkpoint_grad: False
cross_attend: False
cos: False
freeze: null
square: True
bound_embeds: False
use_all_negatives: False
freeze_cntr: False
dist_heads: 1
lora: null
archive: results/0510/models/SERAC_MULTI/llava_250510_221042-step_25000.pt

batch_size: 1
model_save_pt: 5000
edit_bs: 1
silent: False
#max_epochs: 1
max_iters: 50000
log_interval: 1
val_interval: 5000
early_stop_patience: 5000
early_stop_key: "loss/total_edit_val"
eval_only: True
half: False
save: False
debug: False
log_errors: False
unlikelihood: True


val_batch_size: 1
accumulate_bs: 1
val_steps: 1000
opt: Adam
grad_clip: 100.

# Output
results_dir: ./results/models/stage3_1021/comp500_llava_serac

# Multimodal
qformer_checkpoint: null
qformer_name_or_path: null
state_dict_file: null
pretrained_ckpt: null

# image
coco_image: datasets/VLKEB_images/mmkb_images
rephrase_image: datasets/VLKEB_images/mmkb_images